### ISSUE TITLE
Enable controller mode via keyboard

### ISSUE THREAD

**Issue by sakifx9** [goost/coldtranslation#2]
I am using an xbox controller to play the game via remote play and it does not have a touch pad, so I was wondering if you could add an option to enable controller mode some other way

**Comment by goost** [comment]
Unfortunately, I do not own a Xbox Controller and did not know that Remote Play allows you to use another controller besides the PS4 one.
Does it work out of the box or are you using a third party program to emulate a PS4 controller?

**Comment by sakifx9** [comment]
> Unfortunately, I do not own a Xbox Controller and did not know that Remote Play allows you to use another controller besides the PS4 one.
> Does it work out of the box or are you using a third party program to emulate a PS4 controller?

Just using a program to emulate controller, but I think there are workarounds to sacrifice one of the buttons and assign it to the touchpad instead, so this issue can be closed.
