### ISSUE TITLE
Next line for controller mode issues

### ISSUE THREAD

**Issue by ScottyT** [goost/coldtranslation#3]
I just downloaded this last night and since I don't have Sen no Kiseki 4 yet I decided to play this with Cold Steel 3 and the CS3 spreadsheet.  I noticed when using the controller to advance lines of dialog it would take like several seconds to go to the next line.  Keyboard mode doesn't have any lag at all, but it would be nice to use a controller for dialog.  Is there additional steps I'm missing or something else I have to configure to get the controller mode to work smoothly?  

To also clarify this only happens when dialog is up.  I was able to use the left and right dpad to skip the intro text in the spreadsheet.

**Comment by goost** [comment]
Thanks for trying out the program! Sorry to hear that you are experiencing issues.

So, do I understand you correctly:
Changing the lines via the Keyboard works fine, changing the lines via the D-Pad buttons works fine too but changing the lines via the Circle-Button lags?

Do the buttons lag in general? Is the lag only on the line change but not in-game? Does it only lag if there is dialogue up in-game? Does it make a difference if the Controller-Mode is on or off (green/red circle)?

**Comment by ScottyT** [comment]
I will have to test it out some more later today since I can't do it right now.  From my experience changing lines of dialog lags when using the left and right D-Pad buttons as well as the circle button.  I made sure the controller mode was on by touching the touch pad, but it took like several seconds for the red circle to turn green.  

Now I didn't have the spreadsheet inside the folder where the program is and I am thinking that could help.  Also it could be because I had the game running before running the cold translation program, but I would have to try it out later since I haven't had a chance to use it recently.

**Comment by ScottyT** [comment]
I tried this out yesterday and the issues that I have been seeing have been resolved.  Essentially I put the spreadsheet in the same folder as the program and ran the program before connecting remote play to my ps4.

**Comment by goost** [comment]
Thanks for your feedback.  
Sometimes bugs are unfortunately very random and so are the solutions. Glad it got resolved for you.
